spring:
  application:
    name: framework
  data:
    jdbc:
      dialect: maria
  jpa:
    open-in-view: false
app:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  mariadb:
    url: jdbc:mariadb://localhost:3306/mariadb
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1